### ISSUE TITLE
Is there anyway to config in such a way Siri can unlock the car without having to unlock the phone first?

### ISSUE THREAD

**Issue by ssllii** [nfarina/homebridge-tesla#22] opened 2019-06-21 04:07 UTC
Siri understands what I want to do, but tells me I need to unlock the phone first.  Anyway to config homebridge-tesla to tell homekit if ignore the state of the phone?

**Comment by nfarina** [comment] 2019-06-21 04:24
So I believe all "locks" require authentication unfortunately. Personally I use my watch which doesn't require additional auth.

**Comment by ssllii** [comment] 2019-06-21 05:14
Ok.  Somehome Homekit classify garage door as something ok to just open.

When I say Siri "open Model 3" or "unlock Model 3", it unlocks and opens everything, including trunk, frunk and charge port.  What am I missing?

**Comment by nfarina** [comment] 2019-06-21 05:54
I’m having the same issue (of everything opening at once)! Not sure why this is happening all of a sudden. Will investigate.

**Comment by ssllii** [comment] 2019-07-18 01:45
Hi, did you have a chance to figure out what is going on?

**Comment by nfarina** [comment] 2019-07-22 23:25
I spent some time on this today, it's very frustrating to work on because there's no kind of diagnostic to know *why* Siri makes the decisions they make.

However I think I have a clue. Can you try changing the `name` of your car to something unrelated to the names of the various locks and switches? For instance, `"name": "My Car"` instead of "Model 3". I think what's happening is when you say "Open the Model 3", Siri interprets that as wanting to open all the locks on the accessory since that's the accessory's "global" name.

**Comment by mbhforum** [comment] 2019-08-03 10:25
I am having the same issue with the Trunk and Frunk opening when unlocking my car via Siri.  I don't think the name has anything to do with it as the name of my lock/unlock device is "Tesla" and the names of Trunk and Frunk are "Trunk" and "Frunk".  Homebridge is doing something that is grouping all of the devices because if you change the Room of one of the devices, they all change with it.   This is even without Siri, so I believe the underlying issue is it's grouping them somehow.

**Comment by iAnatoly** [comment] 2019-08-03 19:39
Check the room name. I named my room 'Car', and my car 'Tesla'. 
So now 'Unlock Car' unlocks all locks in the room (frunk+trunk+doors), and 'Unlock Tesla' unlocks just the car.

**Comment by mbhforum** [comment] 2019-08-03 20:23
Hmmm, not for me. I just did what you suggested and it did not work like it did for you. I have a Model S.

**Comment by ssllii** [comment] 2019-08-11 23:25
My Connection is now showing up as "no response", and I couldn't see any error in the homebridge log.  Is there any way to turn on more debug for homebridge-tesla?

**Comment by ssllii** [comment] 2019-08-14 06:00
Ok, the "no response" was caused by access token out of date.  I got the new one.
But the overall behavior is flaky, e.g. I can lock/unlock the car, but at the same time I couldn't get battery status nor unlock the charge port...

**Comment by nfarina** [comment] 2019-10-01 22:42
I've reverted the plugin back to a more reliable state, and also provided default names for the various services, which makes it easier for Siri to deal with. I had to remove the Battery service because I believe it was one of the causes for the "flaky" behavior. I'm going to close this for now, give the new version a shot and let me know if anything doesn't work!

**Closed by nfarina** 2019-10-01 22:42 UTC
