### ISSUE TITLE
MFA Passcode?

### ISSUE THREAD

**Issue by danholt-international** [nfarina/homebridge-tesla#70] opened 2021-04-16 13:08 UTC
Hi! Is this PlugIn unusable when 2-factor verification is already activated?
I permenently get an MFA passcode error in hombridge console. And creating a token does nor work either as a passcode is requested.

**Comment by ayn** [comment] 2021-05-01 16:33
`authToken` works for me, I get it from the iOS _Auth app for Tesla_ app, super easy.

**Comment by digivish** [comment] 2021-05-18 18:44
> `authToken` works for me, I get it from the iOS _Auth app for Tesla_ app, super easy.

Yes I can confirm using the token works. I actually used username, password and the authToken and everything fired up for me.

**Comment by ericwastaken** [comment] 2021-10-05 01:00
To add details to the above answers, indeed the iOS app "Auth App for Tesla" allows you to generate an AUTH TOKEN since it uses the TESLA LOGIN which will prompt for 2FA if that's enabled for your account.

The app is here on the Apple App Store: https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613

**Comment by nfarina** [comment] 2021-11-07 01:36
This should be fixed by the latest version (3.0.1) - check the README for details!

**Closed by nfarina** 2021-11-07 01:36 UTC
